config/routes.rb
Rails.application.routes.draw do
  resources :sons
  resources :fathers

  root to: 'fathers#index'

end

app/models/father.rb
class Father < ActiveRecord::Base
  has_many :sons

  has_attached_file :picture, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/assets/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/

  validates :name, presence: true
end

app/models/son.rb
class Son < ActiveRecord::Base
  belongs_to :father

  has_attached_file :picture, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/assets/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/

  validates :name, presence: true
  validates :father_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/fathers_controller.rb
class FathersController < ApplicationController
  before_action :set_father, only: [:show, :edit, :update, :destroy]

  # GET /fathers
  # GET /fathers.json
  def index
    @fathers = Father.page(params[:page])
  end

  # GET /fathers/1
  # GET /fathers/1.json
  def show
  end

  # GET /fathers/new
  def new
    @father = Father.new
  end

  # GET /fathers/1/edit
  def edit
  end

  # POST /fathers
  # POST /fathers.json
  def create
    @father = Father.new(father_params)

    respond_to do |format|
      if @father.save
        format.html { redirect_to @father, notice: 'Father was successfully created.' }
        format.json { render :show, status: :created, location: @father }
      else
        format.html { render :new }
        format.json { render json: @father.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fathers/1
  # PATCH/PUT /fathers/1.json
  def update
    respond_to do |format|
      if @father.update(father_params)
        format.html { redirect_to @father, notice: 'Father was successfully updated.' }
        format.json { render :show, status: :ok, location: @father }
      else
        format.html { render :edit }
        format.json { render json: @father.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fathers/1
  # DELETE /fathers/1.json
  def destroy
    @father.destroy
    respond_to do |format|
      format.html { redirect_to fathers_url, notice: 'Father was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_father
      @father = Father.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def father_params
      params.require(:father).permit(:name, :birth_date, :occupation, :picture)
    end
end

app/controllers/sons_controller.rb
class SonsController < ApplicationController
  before_action :set_son, only: [:show, :edit, :update, :destroy]

  # GET /sons
  # GET /sons.json
  def index
    @sons = Son.page(params[:page])
  end

  # GET /sons/1
  # GET /sons/1.json
  def show
  end

  # GET /sons/new
  def new
    @son = Son.new
  end

  # GET /sons/1/edit
  def edit
  end

  # POST /sons
  # POST /sons.json
  def create
    @son = Son.new(son_params)

    respond_to do |format|
      if @son.save
        format.html { redirect_to @son, notice: 'Son was successfully created.' }
        format.json { render :show, status: :created, location: @son }
      else
        format.html { render :new }
        format.json { render json: @son.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sons/1
  # PATCH/PUT /sons/1.json
  def update
    respond_to do |format|
      if @son.update(son_params)
        format.html { redirect_to @son, notice: 'Son was successfully updated.' }
        format.json { render :show, status: :ok, location: @son }
      else
        format.html { render :edit }
        format.json { render json: @son.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sons/1
  # DELETE /sons/1.json
  def destroy
    @son.destroy
    respond_to do |format|
      format.html { redirect_to sons_url, notice: 'Son was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_son
      @son = Son.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def son_params
      params.require(:son).permit(:name, :birth_date, :occupation, :father_id, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fathers_helper.rb
module FathersHelper
end

app/helpers/sons_helper.rb
module SonsHelper
end

app/views/fathers/_form.html.erb
<%= simple_form_for @father, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= f.input :birth_date %>
  <%= f.input :occupation %>
  <%= f.input :picture, as: :file, input_html: { class: 'form-control' } %>

  <br />
  
  <div class="form-group pull-right">
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")), fathers_path, :class => 'btn btn-default' %>
  	<%= f.button :submit, :class => 'btn-primary' %>
  </div>

<% end %>

app/views/fathers/edit.html.erb
<%- model_class = Father -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/fathers/index.html.erb
<%- model_class = Father -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:birth_date) %></th>
      <th><%= model_class.human_attribute_name(:occupation) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @fathers.each do |father| %>
      <tr>
        <td><%= link_to father.id, father_path(father) %></td>
        <td><%= father.name %></td>
        <td><%= father.birth_date %></td>
        <td><%= father.occupation %></td>
        <td><%=l father.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_father_path(father), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      father_path(father),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br />
<%= paginate @fathers %>
<br />

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_father_path,
            :class => 'btn btn-primary' %>

app/views/fathers/new.html.erb
<%- model_class = Father -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/fathers/show.html.erb
<%- model_class = Father -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @father.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:birth_date) %>:</strong></dt>
  <dd><%= @father.birth_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:occupation) %>:</strong></dt>
  <dd><%= @father.occupation %></dd>
  <dd><%= image_tag @father.picture.url(:medium) %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              fathers_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_father_path(@father), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              father_path(@father),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Pais e filhos - Relacionamentos e testando gems" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%= root_path %>">Pais e Filhos</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Home", root_path  %></li>
            <li><%= link_to "Pais", fathers_path %></li>
            <li><%= link_to "Filhos", sons_path %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Menu Lateral</h3>
            <ul class="nav nav-list">
            	<li><%= link_to "Home", root_path  %></li>
            	<li><%= link_to "Cadastrar novo pai", new_father_path %></li>
            	<li><%= link_to "Cadastrar novo filho", new_son_path %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <br />

      <footer>
        <p>&copy; Elton Santos - 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/sons/_form.html.erb
<%= simple_form_for @son, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= f.input :birth_date %>
  <%= f.input :occupation %>
  <%= f.input :picture, as: :file, input_html: { class: 'form-control' } %>
  <%= f.collection_select(:father_id, Father.all, :id, :name, {prompt: "Selecione um pai"}, {class: "form-group form-control"}) %>
  
  <br />

  <div class="form-group pull-right">
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")), sons_path, :class => 'btn btn-default' %> 
    <%= f.button :submit, :class => 'btn-primary' %>
  </div>
  
<% end %>

app/views/sons/edit.html.erb
<%- model_class = Son -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sons/index.html.erb
<%- model_class = Son -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:birth_date) %></th>
      <th><%= model_class.human_attribute_name(:occupation) %></th>
      <th><%= model_class.human_attribute_name(:father_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @sons.each do |son| %>
      <tr>
        <td><%= link_to son.id, son_path(son) %></td>
        <td><%= son.name %></td>
        <td><%= son.birth_date %></td>
        <td><%= son.occupation %></td>
        <td><%= son.father.name %></td>
        <td><%=l son.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_son_path(son), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      son_path(son),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br />
<%= paginate @sons %>
<br />

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_son_path,
            :class => 'btn btn-primary' %>

app/views/sons/new.html.erb
<%- model_class = Son -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sons/show.html.erb
<%- model_class = Son -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @son.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:birth_date) %>:</strong></dt>
  <dd><%= @son.birth_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:occupation) %>:</strong></dt>
  <dd><%= @son.occupation %></dd>
  <dt><strong><%= model_class.human_attribute_name(:father_id) %>:</strong></dt>
  <dd><%= @son.father.name %></dd>
  <dd><%= image_tag @son.picture.url(:medium) %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              sons_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_son_path(@son), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              son_path(@son),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>